


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Unity.Collections.LowLevel.Unsafe;
using Unity.Burst;
using System;

namespace CareBoo.Burst.Delegates
{

    public unsafe readonly struct BurstAction : IAction
        
    {
#if !UNITY_DOTSPLAYER
        [NativeDisableUnsafePtrRestriction]
#endif
        readonly IntPtr _ptr;

        BurstAction(IntPtr ptr) => _ptr = ptr;

        public void Invoke()
        {
            bool isBurst = false;
            Unity.Burst.CompilerServices.Hint.Assume(isBurst);
            if (!isBurst)
            {
                Invoke_Dotnet();
                return;
            }
            Invoke_Burst();
        }

        void Invoke_Burst()
        {
            new FunctionPointer<Action>(_ptr).Invoke();
        }

        [BurstDiscard]
        void Invoke_Dotnet()
        {
            ((delegate*<void>)_ptr)();
        }

        public static BurstAction Compile(Action action)
        {
            return BurstCompiler.CompileFunctionPointer(action);
        }

        public static implicit operator BurstAction(FunctionPointer<Action> unityFunctionPointer)
        {
            return new BurstAction(unityFunctionPointer.Value);
        }

        public static implicit operator FunctionPointer<Action>(BurstAction burstAction)
        {
            return new FunctionPointer<Action>(burstAction._ptr);
        }
    }

    public unsafe readonly struct BurstAction<T> : IAction<T>
        
        where T : struct
    {
#if !UNITY_DOTSPLAYER
        [NativeDisableUnsafePtrRestriction]
#endif
        readonly IntPtr _ptr;

        BurstAction(IntPtr ptr) => _ptr = ptr;

        public void Invoke(T arg0)
        {
            bool isBurst = false;
            Unity.Burst.CompilerServices.Hint.Assume(isBurst);
            if (!isBurst)
            {
                Invoke_Dotnet(arg0);
                return;
            }
            Invoke_Burst(arg0);
        }

        void Invoke_Burst(T arg0)
        {
            new FunctionPointer<Action<T>>(_ptr).Invoke(arg0);
        }

        [BurstDiscard]
        void Invoke_Dotnet(T arg0)
        {
            ((delegate*<T, void>)_ptr)(arg0);
        }

        public static BurstAction<T> Compile(Action<T> action)
        {
            return BurstCompiler.CompileFunctionPointer(action);
        }

        public static implicit operator BurstAction<T>(FunctionPointer<Action<T>> unityFunctionPointer)
        {
            return new BurstAction<T>(unityFunctionPointer.Value);
        }

        public static implicit operator FunctionPointer<Action<T>>(BurstAction<T> burstAction)
        {
            return new FunctionPointer<Action<T>>(burstAction._ptr);
        }
    }

    public unsafe readonly struct BurstAction<T, U> : IAction<T, U>
        
        where T : struct
        where U : struct
    {
#if !UNITY_DOTSPLAYER
        [NativeDisableUnsafePtrRestriction]
#endif
        readonly IntPtr _ptr;

        BurstAction(IntPtr ptr) => _ptr = ptr;

        public void Invoke(T arg0, U arg1)
        {
            bool isBurst = false;
            Unity.Burst.CompilerServices.Hint.Assume(isBurst);
            if (!isBurst)
            {
                Invoke_Dotnet(arg0, arg1);
                return;
            }
            Invoke_Burst(arg0, arg1);
        }

        void Invoke_Burst(T arg0, U arg1)
        {
            new FunctionPointer<Action<T, U>>(_ptr).Invoke(arg0, arg1);
        }

        [BurstDiscard]
        void Invoke_Dotnet(T arg0, U arg1)
        {
            ((delegate*<T, U, void>)_ptr)(arg0, arg1);
        }

        public static BurstAction<T, U> Compile(Action<T, U> action)
        {
            return BurstCompiler.CompileFunctionPointer(action);
        }

        public static implicit operator BurstAction<T, U>(FunctionPointer<Action<T, U>> unityFunctionPointer)
        {
            return new BurstAction<T, U>(unityFunctionPointer.Value);
        }

        public static implicit operator FunctionPointer<Action<T, U>>(BurstAction<T, U> burstAction)
        {
            return new FunctionPointer<Action<T, U>>(burstAction._ptr);
        }
    }

    public unsafe readonly struct BurstAction<T, U, V> : IAction<T, U, V>
        
        where T : struct
        where U : struct
        where V : struct
    {
#if !UNITY_DOTSPLAYER
        [NativeDisableUnsafePtrRestriction]
#endif
        readonly IntPtr _ptr;

        BurstAction(IntPtr ptr) => _ptr = ptr;

        public void Invoke(T arg0, U arg1, V arg2)
        {
            bool isBurst = false;
            Unity.Burst.CompilerServices.Hint.Assume(isBurst);
            if (!isBurst)
            {
                Invoke_Dotnet(arg0, arg1, arg2);
                return;
            }
            Invoke_Burst(arg0, arg1, arg2);
        }

        void Invoke_Burst(T arg0, U arg1, V arg2)
        {
            new FunctionPointer<Action<T, U, V>>(_ptr).Invoke(arg0, arg1, arg2);
        }

        [BurstDiscard]
        void Invoke_Dotnet(T arg0, U arg1, V arg2)
        {
            ((delegate*<T, U, V, void>)_ptr)(arg0, arg1, arg2);
        }

        public static BurstAction<T, U, V> Compile(Action<T, U, V> action)
        {
            return BurstCompiler.CompileFunctionPointer(action);
        }

        public static implicit operator BurstAction<T, U, V>(FunctionPointer<Action<T, U, V>> unityFunctionPointer)
        {
            return new BurstAction<T, U, V>(unityFunctionPointer.Value);
        }

        public static implicit operator FunctionPointer<Action<T, U, V>>(BurstAction<T, U, V> burstAction)
        {
            return new FunctionPointer<Action<T, U, V>>(burstAction._ptr);
        }
    }

    public unsafe readonly struct BurstAction<T, U, V, W> : IAction<T, U, V, W>
        
        where T : struct
        where U : struct
        where V : struct
        where W : struct
    {
#if !UNITY_DOTSPLAYER
        [NativeDisableUnsafePtrRestriction]
#endif
        readonly IntPtr _ptr;

        BurstAction(IntPtr ptr) => _ptr = ptr;

        public void Invoke(T arg0, U arg1, V arg2, W arg3)
        {
            bool isBurst = false;
            Unity.Burst.CompilerServices.Hint.Assume(isBurst);
            if (!isBurst)
            {
                Invoke_Dotnet(arg0, arg1, arg2, arg3);
                return;
            }
            Invoke_Burst(arg0, arg1, arg2, arg3);
        }

        void Invoke_Burst(T arg0, U arg1, V arg2, W arg3)
        {
            new FunctionPointer<Action<T, U, V, W>>(_ptr).Invoke(arg0, arg1, arg2, arg3);
        }

        [BurstDiscard]
        void Invoke_Dotnet(T arg0, U arg1, V arg2, W arg3)
        {
            ((delegate*<T, U, V, W, void>)_ptr)(arg0, arg1, arg2, arg3);
        }

        public static BurstAction<T, U, V, W> Compile(Action<T, U, V, W> action)
        {
            return BurstCompiler.CompileFunctionPointer(action);
        }

        public static implicit operator BurstAction<T, U, V, W>(FunctionPointer<Action<T, U, V, W>> unityFunctionPointer)
        {
            return new BurstAction<T, U, V, W>(unityFunctionPointer.Value);
        }

        public static implicit operator FunctionPointer<Action<T, U, V, W>>(BurstAction<T, U, V, W> burstAction)
        {
            return new FunctionPointer<Action<T, U, V, W>>(burstAction._ptr);
        }
    }

    public unsafe readonly struct BurstAction<T, U, V, W, X> : IAction<T, U, V, W, X>
        
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where X : struct
    {
#if !UNITY_DOTSPLAYER
        [NativeDisableUnsafePtrRestriction]
#endif
        readonly IntPtr _ptr;

        BurstAction(IntPtr ptr) => _ptr = ptr;

        public void Invoke(T arg0, U arg1, V arg2, W arg3, X arg4)
        {
            bool isBurst = false;
            Unity.Burst.CompilerServices.Hint.Assume(isBurst);
            if (!isBurst)
            {
                Invoke_Dotnet(arg0, arg1, arg2, arg3, arg4);
                return;
            }
            Invoke_Burst(arg0, arg1, arg2, arg3, arg4);
        }

        void Invoke_Burst(T arg0, U arg1, V arg2, W arg3, X arg4)
        {
            new FunctionPointer<Action<T, U, V, W, X>>(_ptr).Invoke(arg0, arg1, arg2, arg3, arg4);
        }

        [BurstDiscard]
        void Invoke_Dotnet(T arg0, U arg1, V arg2, W arg3, X arg4)
        {
            ((delegate*<T, U, V, W, X, void>)_ptr)(arg0, arg1, arg2, arg3, arg4);
        }

        public static BurstAction<T, U, V, W, X> Compile(Action<T, U, V, W, X> action)
        {
            return BurstCompiler.CompileFunctionPointer(action);
        }

        public static implicit operator BurstAction<T, U, V, W, X>(FunctionPointer<Action<T, U, V, W, X>> unityFunctionPointer)
        {
            return new BurstAction<T, U, V, W, X>(unityFunctionPointer.Value);
        }

        public static implicit operator FunctionPointer<Action<T, U, V, W, X>>(BurstAction<T, U, V, W, X> burstAction)
        {
            return new FunctionPointer<Action<T, U, V, W, X>>(burstAction._ptr);
        }
    }

    public unsafe readonly struct BurstAction<T, U, V, W, X, Y> : IAction<T, U, V, W, X, Y>
        
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where X : struct
        where Y : struct
    {
#if !UNITY_DOTSPLAYER
        [NativeDisableUnsafePtrRestriction]
#endif
        readonly IntPtr _ptr;

        BurstAction(IntPtr ptr) => _ptr = ptr;

        public void Invoke(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5)
        {
            bool isBurst = false;
            Unity.Burst.CompilerServices.Hint.Assume(isBurst);
            if (!isBurst)
            {
                Invoke_Dotnet(arg0, arg1, arg2, arg3, arg4, arg5);
                return;
            }
            Invoke_Burst(arg0, arg1, arg2, arg3, arg4, arg5);
        }

        void Invoke_Burst(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5)
        {
            new FunctionPointer<Action<T, U, V, W, X, Y>>(_ptr).Invoke(arg0, arg1, arg2, arg3, arg4, arg5);
        }

        [BurstDiscard]
        void Invoke_Dotnet(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5)
        {
            ((delegate*<T, U, V, W, X, Y, void>)_ptr)(arg0, arg1, arg2, arg3, arg4, arg5);
        }

        public static BurstAction<T, U, V, W, X, Y> Compile(Action<T, U, V, W, X, Y> action)
        {
            return BurstCompiler.CompileFunctionPointer(action);
        }

        public static implicit operator BurstAction<T, U, V, W, X, Y>(FunctionPointer<Action<T, U, V, W, X, Y>> unityFunctionPointer)
        {
            return new BurstAction<T, U, V, W, X, Y>(unityFunctionPointer.Value);
        }

        public static implicit operator FunctionPointer<Action<T, U, V, W, X, Y>>(BurstAction<T, U, V, W, X, Y> burstAction)
        {
            return new FunctionPointer<Action<T, U, V, W, X, Y>>(burstAction._ptr);
        }
    }

    public unsafe readonly struct BurstAction<T, U, V, W, X, Y, Z> : IAction<T, U, V, W, X, Y, Z>
        
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where X : struct
        where Y : struct
        where Z : struct
    {
#if !UNITY_DOTSPLAYER
        [NativeDisableUnsafePtrRestriction]
#endif
        readonly IntPtr _ptr;

        BurstAction(IntPtr ptr) => _ptr = ptr;

        public void Invoke(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5, Z arg6)
        {
            bool isBurst = false;
            Unity.Burst.CompilerServices.Hint.Assume(isBurst);
            if (!isBurst)
            {
                Invoke_Dotnet(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return;
            }
            Invoke_Burst(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
        }

        void Invoke_Burst(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5, Z arg6)
        {
            new FunctionPointer<Action<T, U, V, W, X, Y, Z>>(_ptr).Invoke(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
        }

        [BurstDiscard]
        void Invoke_Dotnet(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5, Z arg6)
        {
            ((delegate*<T, U, V, W, X, Y, Z, void>)_ptr)(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
        }

        public static BurstAction<T, U, V, W, X, Y, Z> Compile(Action<T, U, V, W, X, Y, Z> action)
        {
            return BurstCompiler.CompileFunctionPointer(action);
        }

        public static implicit operator BurstAction<T, U, V, W, X, Y, Z>(FunctionPointer<Action<T, U, V, W, X, Y, Z>> unityFunctionPointer)
        {
            return new BurstAction<T, U, V, W, X, Y, Z>(unityFunctionPointer.Value);
        }

        public static implicit operator FunctionPointer<Action<T, U, V, W, X, Y, Z>>(BurstAction<T, U, V, W, X, Y, Z> burstAction)
        {
            return new FunctionPointer<Action<T, U, V, W, X, Y, Z>>(burstAction._ptr);
        }
    }

}
