
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Unity.Burst;
using static CareBoo.Burst.Delegates.SafetyChecks;

namespace CareBoo.Burst.Delegates
{
    public struct BurstFunc<TResult>
        : IFunc<TResult>
        where TResult : struct
    {
        readonly FunctionPointer<Func<TResult>> functionPointer;

        public BurstFunc(FunctionPointer<Func<TResult>> functionPointer)
        {
            this.functionPointer = functionPointer;
        }

        public TResult Invoke()
        {
            SupportedInBurstOnly();
            return functionPointer.Invoke();
        }
    }

    public struct BurstFunc<T, TResult>
        : IFunc<T, TResult>
        where T : struct
        where TResult : struct
    {
        readonly FunctionPointer<Func<T, TResult>> functionPointer;

        public BurstFunc(FunctionPointer<Func<T, TResult>> functionPointer)
        {
            this.functionPointer = functionPointer;
        }

        public TResult Invoke(T arg0)
        {
            SupportedInBurstOnly();
            return functionPointer.Invoke(arg0);
        }
    }

    public struct BurstFunc<T, U, TResult>
        : IFunc<T, U, TResult>
        where T : struct
        where U : struct
        where TResult : struct
    {
        readonly FunctionPointer<Func<T, U, TResult>> functionPointer;

        public BurstFunc(FunctionPointer<Func<T, U, TResult>> functionPointer)
        {
            this.functionPointer = functionPointer;
        }

        public TResult Invoke(T arg0, U arg1)
        {
            SupportedInBurstOnly();
            return functionPointer.Invoke(arg0, arg1);
        }
    }

    public struct BurstFunc<T, U, V, TResult>
        : IFunc<T, U, V, TResult>
        where T : struct
        where U : struct
        where V : struct
        where TResult : struct
    {
        readonly FunctionPointer<Func<T, U, V, TResult>> functionPointer;

        public BurstFunc(FunctionPointer<Func<T, U, V, TResult>> functionPointer)
        {
            this.functionPointer = functionPointer;
        }

        public TResult Invoke(T arg0, U arg1, V arg2)
        {
            SupportedInBurstOnly();
            return functionPointer.Invoke(arg0, arg1, arg2);
        }
    }

    public struct BurstFunc<T, U, V, W, TResult>
        : IFunc<T, U, V, W, TResult>
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where TResult : struct
    {
        readonly FunctionPointer<Func<T, U, V, W, TResult>> functionPointer;

        public BurstFunc(FunctionPointer<Func<T, U, V, W, TResult>> functionPointer)
        {
            this.functionPointer = functionPointer;
        }

        public TResult Invoke(T arg0, U arg1, V arg2, W arg3)
        {
            SupportedInBurstOnly();
            return functionPointer.Invoke(arg0, arg1, arg2, arg3);
        }
    }

    public struct BurstFunc<T, U, V, W, X, TResult>
        : IFunc<T, U, V, W, X, TResult>
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where X : struct
        where TResult : struct
    {
        readonly FunctionPointer<Func<T, U, V, W, X, TResult>> functionPointer;

        public BurstFunc(FunctionPointer<Func<T, U, V, W, X, TResult>> functionPointer)
        {
            this.functionPointer = functionPointer;
        }

        public TResult Invoke(T arg0, U arg1, V arg2, W arg3, X arg4)
        {
            SupportedInBurstOnly();
            return functionPointer.Invoke(arg0, arg1, arg2, arg3, arg4);
        }
    }

    public struct BurstFunc<T, U, V, W, X, Y, TResult>
        : IFunc<T, U, V, W, X, Y, TResult>
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where X : struct
        where Y : struct
        where TResult : struct
    {
        readonly FunctionPointer<Func<T, U, V, W, X, Y, TResult>> functionPointer;

        public BurstFunc(FunctionPointer<Func<T, U, V, W, X, Y, TResult>> functionPointer)
        {
            this.functionPointer = functionPointer;
        }

        public TResult Invoke(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5)
        {
            SupportedInBurstOnly();
            return functionPointer.Invoke(arg0, arg1, arg2, arg3, arg4, arg5);
        }
    }

    public struct BurstFunc<T, U, V, W, X, Y, Z, TResult>
        : IFunc<T, U, V, W, X, Y, Z, TResult>
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where X : struct
        where Y : struct
        where Z : struct
        where TResult : struct
    {
        readonly FunctionPointer<Func<T, U, V, W, X, Y, Z, TResult>> functionPointer;

        public BurstFunc(FunctionPointer<Func<T, U, V, W, X, Y, Z, TResult>> functionPointer)
        {
            this.functionPointer = functionPointer;
        }

        public TResult Invoke(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5, Z arg6)
        {
            SupportedInBurstOnly();
            return functionPointer.Invoke(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
        }
    }

}