//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




using Unity.Burst;
using System.Runtime.InteropServices;

namespace CareBoo.Burst.Delegates
{

    public readonly struct ValueAction
    {
        public readonly struct Impl<TLambda>
            where TLambda : struct, IAction
        {
            internal readonly TLambda lambda;

            public void Invoke()
            {
                lambda.Invoke();
            }

            internal Impl(TLambda lambda)
            {
                this.lambda = lambda;
            }

        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void Delegate();

        public static Impl<TLambda> New<TLambda>(TLambda lambda = default)
            where TLambda : struct, IAction
        {
            return new Impl<TLambda>(lambda);
        }

        public static Impl<BurstAction> Compile(Delegate action)
        {
            var ptr = BurstCompiler.CompileFunctionPointer(action);
            var burstAction = new BurstAction(ptr.Value);
            return New(burstAction);
        }
    }


    public readonly struct ValueAction<T>
        where T : struct
    {
        public readonly struct Impl<TLambda>
            where TLambda : struct, IAction<T>
        {
            internal readonly TLambda lambda;

            public void Invoke(T arg0)
            {
                lambda.Invoke(arg0);
            }

            internal Impl(TLambda lambda)
            {
                this.lambda = lambda;
            }

            public ValueAction.Impl<Closure<T>.AppliedToAction<TLambda>> Apply(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToAction<TLambda>(
                    arg0,
                    this
                );
                return ValueAction.New(closure);
            }

        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void Delegate(T arg0);

        public static Impl<TLambda> New<TLambda>(TLambda lambda = default)
            where TLambda : struct, IAction<T>
        {
            return new Impl<TLambda>(lambda);
        }

        public static Impl<BurstAction<T>> Compile(Delegate action)
        {
            var ptr = BurstCompiler.CompileFunctionPointer(action);
            var burstAction = new BurstAction<T>(ptr.Value);
            return New(burstAction);
        }
    }


    public readonly struct ValueAction<T, U>
        where T : struct
        where U : struct
    {
        public readonly struct Impl<TLambda>
            where TLambda : struct, IAction<T, U>
        {
            internal readonly TLambda lambda;

            public void Invoke(T arg0, U arg1)
            {
                lambda.Invoke(arg0, arg1);
            }

            internal Impl(TLambda lambda)
            {
                this.lambda = lambda;
            }

            public ValueAction<U>.Impl<Closure<T>.AppliedToAction<U, TLambda>> Apply(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToAction<U, TLambda>(
                    arg0,
                    this
                );
                return ValueAction<U>.New(closure);
            }

            public ValueAction.Impl<Closure<T, U>.AppliedToAction<TLambda>> Apply(
                T arg0,
                U arg1
                )
            {
                var closure = new Closure<T, U>.AppliedToAction<TLambda>(
                    arg0,
                    arg1,
                    this
                );
                return ValueAction.New(closure);
            }

        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void Delegate(T arg0, U arg1);

        public static Impl<TLambda> New<TLambda>(TLambda lambda = default)
            where TLambda : struct, IAction<T, U>
        {
            return new Impl<TLambda>(lambda);
        }

        public static Impl<BurstAction<T, U>> Compile(Delegate action)
        {
            var ptr = BurstCompiler.CompileFunctionPointer(action);
            var burstAction = new BurstAction<T, U>(ptr.Value);
            return New(burstAction);
        }
    }


    public readonly struct ValueAction<T, U, V>
        where T : struct
        where U : struct
        where V : struct
    {
        public readonly struct Impl<TLambda>
            where TLambda : struct, IAction<T, U, V>
        {
            internal readonly TLambda lambda;

            public void Invoke(T arg0, U arg1, V arg2)
            {
                lambda.Invoke(arg0, arg1, arg2);
            }

            internal Impl(TLambda lambda)
            {
                this.lambda = lambda;
            }

            public ValueAction<U, V>.Impl<Closure<T>.AppliedToAction<U, V, TLambda>> Apply(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToAction<U, V, TLambda>(
                    arg0,
                    this
                );
                return ValueAction<U, V>.New(closure);
            }

            public ValueAction<V>.Impl<Closure<T, U>.AppliedToAction<V, TLambda>> Apply(
                T arg0,
                U arg1
                )
            {
                var closure = new Closure<T, U>.AppliedToAction<V, TLambda>(
                    arg0,
                    arg1,
                    this
                );
                return ValueAction<V>.New(closure);
            }

            public ValueAction.Impl<Closure<T, U, V>.AppliedToAction<TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2
                )
            {
                var closure = new Closure<T, U, V>.AppliedToAction<TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    this
                );
                return ValueAction.New(closure);
            }

        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void Delegate(T arg0, U arg1, V arg2);

        public static Impl<TLambda> New<TLambda>(TLambda lambda = default)
            where TLambda : struct, IAction<T, U, V>
        {
            return new Impl<TLambda>(lambda);
        }

        public static Impl<BurstAction<T, U, V>> Compile(Delegate action)
        {
            var ptr = BurstCompiler.CompileFunctionPointer(action);
            var burstAction = new BurstAction<T, U, V>(ptr.Value);
            return New(burstAction);
        }
    }


    public readonly struct ValueAction<T, U, V, W>
        where T : struct
        where U : struct
        where V : struct
        where W : struct
    {
        public readonly struct Impl<TLambda>
            where TLambda : struct, IAction<T, U, V, W>
        {
            internal readonly TLambda lambda;

            public void Invoke(T arg0, U arg1, V arg2, W arg3)
            {
                lambda.Invoke(arg0, arg1, arg2, arg3);
            }

            internal Impl(TLambda lambda)
            {
                this.lambda = lambda;
            }

            public ValueAction<U, V, W>.Impl<Closure<T>.AppliedToAction<U, V, W, TLambda>> Apply(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToAction<U, V, W, TLambda>(
                    arg0,
                    this
                );
                return ValueAction<U, V, W>.New(closure);
            }

            public ValueAction<V, W>.Impl<Closure<T, U>.AppliedToAction<V, W, TLambda>> Apply(
                T arg0,
                U arg1
                )
            {
                var closure = new Closure<T, U>.AppliedToAction<V, W, TLambda>(
                    arg0,
                    arg1,
                    this
                );
                return ValueAction<V, W>.New(closure);
            }

            public ValueAction<W>.Impl<Closure<T, U, V>.AppliedToAction<W, TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2
                )
            {
                var closure = new Closure<T, U, V>.AppliedToAction<W, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    this
                );
                return ValueAction<W>.New(closure);
            }

            public ValueAction.Impl<Closure<T, U, V, W>.AppliedToAction<TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2,
                W arg3
                )
            {
                var closure = new Closure<T, U, V, W>.AppliedToAction<TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    this
                );
                return ValueAction.New(closure);
            }

        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void Delegate(T arg0, U arg1, V arg2, W arg3);

        public static Impl<TLambda> New<TLambda>(TLambda lambda = default)
            where TLambda : struct, IAction<T, U, V, W>
        {
            return new Impl<TLambda>(lambda);
        }

        public static Impl<BurstAction<T, U, V, W>> Compile(Delegate action)
        {
            var ptr = BurstCompiler.CompileFunctionPointer(action);
            var burstAction = new BurstAction<T, U, V, W>(ptr.Value);
            return New(burstAction);
        }
    }


    public readonly struct ValueAction<T, U, V, W, X>
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where X : struct
    {
        public readonly struct Impl<TLambda>
            where TLambda : struct, IAction<T, U, V, W, X>
        {
            internal readonly TLambda lambda;

            public void Invoke(T arg0, U arg1, V arg2, W arg3, X arg4)
            {
                lambda.Invoke(arg0, arg1, arg2, arg3, arg4);
            }

            internal Impl(TLambda lambda)
            {
                this.lambda = lambda;
            }

            public ValueAction<U, V, W, X>.Impl<Closure<T>.AppliedToAction<U, V, W, X, TLambda>> Apply(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToAction<U, V, W, X, TLambda>(
                    arg0,
                    this
                );
                return ValueAction<U, V, W, X>.New(closure);
            }

            public ValueAction<V, W, X>.Impl<Closure<T, U>.AppliedToAction<V, W, X, TLambda>> Apply(
                T arg0,
                U arg1
                )
            {
                var closure = new Closure<T, U>.AppliedToAction<V, W, X, TLambda>(
                    arg0,
                    arg1,
                    this
                );
                return ValueAction<V, W, X>.New(closure);
            }

            public ValueAction<W, X>.Impl<Closure<T, U, V>.AppliedToAction<W, X, TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2
                )
            {
                var closure = new Closure<T, U, V>.AppliedToAction<W, X, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    this
                );
                return ValueAction<W, X>.New(closure);
            }

            public ValueAction<X>.Impl<Closure<T, U, V, W>.AppliedToAction<X, TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2,
                W arg3
                )
            {
                var closure = new Closure<T, U, V, W>.AppliedToAction<X, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    this
                );
                return ValueAction<X>.New(closure);
            }

            public ValueAction.Impl<Closure<T, U, V, W, X>.AppliedToAction<TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2,
                W arg3,
                X arg4
                )
            {
                var closure = new Closure<T, U, V, W, X>.AppliedToAction<TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4,
                    this
                );
                return ValueAction.New(closure);
            }

        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void Delegate(T arg0, U arg1, V arg2, W arg3, X arg4);

        public static Impl<TLambda> New<TLambda>(TLambda lambda = default)
            where TLambda : struct, IAction<T, U, V, W, X>
        {
            return new Impl<TLambda>(lambda);
        }

        public static Impl<BurstAction<T, U, V, W, X>> Compile(Delegate action)
        {
            var ptr = BurstCompiler.CompileFunctionPointer(action);
            var burstAction = new BurstAction<T, U, V, W, X>(ptr.Value);
            return New(burstAction);
        }
    }


    public readonly struct ValueAction<T, U, V, W, X, Y>
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where X : struct
        where Y : struct
    {
        public readonly struct Impl<TLambda>
            where TLambda : struct, IAction<T, U, V, W, X, Y>
        {
            internal readonly TLambda lambda;

            public void Invoke(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5)
            {
                lambda.Invoke(arg0, arg1, arg2, arg3, arg4, arg5);
            }

            internal Impl(TLambda lambda)
            {
                this.lambda = lambda;
            }

            public ValueAction<U, V, W, X, Y>.Impl<Closure<T>.AppliedToAction<U, V, W, X, Y, TLambda>> Apply(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToAction<U, V, W, X, Y, TLambda>(
                    arg0,
                    this
                );
                return ValueAction<U, V, W, X, Y>.New(closure);
            }

            public ValueAction<V, W, X, Y>.Impl<Closure<T, U>.AppliedToAction<V, W, X, Y, TLambda>> Apply(
                T arg0,
                U arg1
                )
            {
                var closure = new Closure<T, U>.AppliedToAction<V, W, X, Y, TLambda>(
                    arg0,
                    arg1,
                    this
                );
                return ValueAction<V, W, X, Y>.New(closure);
            }

            public ValueAction<W, X, Y>.Impl<Closure<T, U, V>.AppliedToAction<W, X, Y, TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2
                )
            {
                var closure = new Closure<T, U, V>.AppliedToAction<W, X, Y, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    this
                );
                return ValueAction<W, X, Y>.New(closure);
            }

            public ValueAction<X, Y>.Impl<Closure<T, U, V, W>.AppliedToAction<X, Y, TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2,
                W arg3
                )
            {
                var closure = new Closure<T, U, V, W>.AppliedToAction<X, Y, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    this
                );
                return ValueAction<X, Y>.New(closure);
            }

            public ValueAction<Y>.Impl<Closure<T, U, V, W, X>.AppliedToAction<Y, TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2,
                W arg3,
                X arg4
                )
            {
                var closure = new Closure<T, U, V, W, X>.AppliedToAction<Y, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4,
                    this
                );
                return ValueAction<Y>.New(closure);
            }

            public ValueAction.Impl<Closure<T, U, V, W, X, Y>.AppliedToAction<TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2,
                W arg3,
                X arg4,
                Y arg5
                )
            {
                var closure = new Closure<T, U, V, W, X, Y>.AppliedToAction<TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4,
                    arg5,
                    this
                );
                return ValueAction.New(closure);
            }

        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void Delegate(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5);

        public static Impl<TLambda> New<TLambda>(TLambda lambda = default)
            where TLambda : struct, IAction<T, U, V, W, X, Y>
        {
            return new Impl<TLambda>(lambda);
        }

        public static Impl<BurstAction<T, U, V, W, X, Y>> Compile(Delegate action)
        {
            var ptr = BurstCompiler.CompileFunctionPointer(action);
            var burstAction = new BurstAction<T, U, V, W, X, Y>(ptr.Value);
            return New(burstAction);
        }
    }


    public readonly struct ValueAction<T, U, V, W, X, Y, Z>
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where X : struct
        where Y : struct
        where Z : struct
    {
        public readonly struct Impl<TLambda>
            where TLambda : struct, IAction<T, U, V, W, X, Y, Z>
        {
            internal readonly TLambda lambda;

            public void Invoke(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5, Z arg6)
            {
                lambda.Invoke(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            }

            internal Impl(TLambda lambda)
            {
                this.lambda = lambda;
            }

            public ValueAction<U, V, W, X, Y, Z>.Impl<Closure<T>.AppliedToAction<U, V, W, X, Y, Z, TLambda>> Apply(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToAction<U, V, W, X, Y, Z, TLambda>(
                    arg0,
                    this
                );
                return ValueAction<U, V, W, X, Y, Z>.New(closure);
            }

            public ValueAction<V, W, X, Y, Z>.Impl<Closure<T, U>.AppliedToAction<V, W, X, Y, Z, TLambda>> Apply(
                T arg0,
                U arg1
                )
            {
                var closure = new Closure<T, U>.AppliedToAction<V, W, X, Y, Z, TLambda>(
                    arg0,
                    arg1,
                    this
                );
                return ValueAction<V, W, X, Y, Z>.New(closure);
            }

            public ValueAction<W, X, Y, Z>.Impl<Closure<T, U, V>.AppliedToAction<W, X, Y, Z, TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2
                )
            {
                var closure = new Closure<T, U, V>.AppliedToAction<W, X, Y, Z, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    this
                );
                return ValueAction<W, X, Y, Z>.New(closure);
            }

            public ValueAction<X, Y, Z>.Impl<Closure<T, U, V, W>.AppliedToAction<X, Y, Z, TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2,
                W arg3
                )
            {
                var closure = new Closure<T, U, V, W>.AppliedToAction<X, Y, Z, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    this
                );
                return ValueAction<X, Y, Z>.New(closure);
            }

            public ValueAction<Y, Z>.Impl<Closure<T, U, V, W, X>.AppliedToAction<Y, Z, TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2,
                W arg3,
                X arg4
                )
            {
                var closure = new Closure<T, U, V, W, X>.AppliedToAction<Y, Z, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4,
                    this
                );
                return ValueAction<Y, Z>.New(closure);
            }

            public ValueAction<Z>.Impl<Closure<T, U, V, W, X, Y>.AppliedToAction<Z, TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2,
                W arg3,
                X arg4,
                Y arg5
                )
            {
                var closure = new Closure<T, U, V, W, X, Y>.AppliedToAction<Z, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4,
                    arg5,
                    this
                );
                return ValueAction<Z>.New(closure);
            }

            public ValueAction.Impl<Closure<T, U, V, W, X, Y, Z>.AppliedToAction<TLambda>> Apply(
                T arg0,
                U arg1,
                V arg2,
                W arg3,
                X arg4,
                Y arg5,
                Z arg6
                )
            {
                var closure = new Closure<T, U, V, W, X, Y, Z>.AppliedToAction<TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4,
                    arg5,
                    arg6,
                    this
                );
                return ValueAction.New(closure);
            }

        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void Delegate(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5, Z arg6);

        public static Impl<TLambda> New<TLambda>(TLambda lambda = default)
            where TLambda : struct, IAction<T, U, V, W, X, Y, Z>
        {
            return new Impl<TLambda>(lambda);
        }

        public static Impl<BurstAction<T, U, V, W, X, Y, Z>> Compile(Delegate action)
        {
            var ptr = BurstCompiler.CompileFunctionPointer(action);
            var burstAction = new BurstAction<T, U, V, W, X, Y, Z>(ptr.Value);
            return New(burstAction);
        }
    }


}
