//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.CompilerServices;

namespace CareBoo.Burst.Delegates
{

    public struct ValueFunc<TResult>
        where TResult : struct
    {
        public readonly ref struct Impl<TLambda>
            where TLambda : struct, IFunc<TResult>
        {
            public readonly TLambda Lambda;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public TResult Invoke()
            {
                return Lambda.Invoke();
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal Impl(TLambda Lambda)
            {
                this.Lambda = Lambda;
            }

        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Impl<TLambda> New<TLambda>(TLambda Lambda = default)
            where TLambda : struct, IFunc<TResult>
        {
            return new Impl<TLambda>(Lambda);
        }
    }


    public struct ValueFunc<T, TResult>
        where T : struct
        where TResult : struct
    {
        public readonly ref struct Impl<TLambda>
            where TLambda : struct, IFunc<T, TResult>
        {
            public readonly TLambda Lambda;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public TResult Invoke(T arg0)
            {
                return Lambda.Invoke(arg0);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal Impl(TLambda Lambda)
            {
                this.Lambda = Lambda;
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<TResult>.Impl<Closure<T>.AppliedToFunc<TResult, TLambda>> PartialInvoke(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToFunc<TResult, TLambda>(
                    arg0,
                    in this
                );
                return ValueFunc<TResult>.New(closure);
            }

        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Impl<TLambda> New<TLambda>(TLambda Lambda = default)
            where TLambda : struct, IFunc<T, TResult>
        {
            return new Impl<TLambda>(Lambda);
        }
    }


    public struct ValueFunc<T, U, TResult>
        where T : struct
        where U : struct
        where TResult : struct
    {
        public readonly ref struct Impl<TLambda>
            where TLambda : struct, IFunc<T, U, TResult>
        {
            public readonly TLambda Lambda;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public TResult Invoke(T arg0, U arg1)
            {
                return Lambda.Invoke(arg0, arg1);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal Impl(TLambda Lambda)
            {
                this.Lambda = Lambda;
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<U, TResult>.Impl<Closure<T>.AppliedToFunc<U, TResult, TLambda>> PartialInvoke(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToFunc<U, TResult, TLambda>(
                    arg0,
                    in this
                );
                return ValueFunc<U, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<TResult>.Impl<Closure<T, U>.AppliedToFunc<TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1
                )
            {
                var closure = new Closure<T, U>.AppliedToFunc<TResult, TLambda>(
                    arg0,
                    arg1,
                    in this
                );
                return ValueFunc<TResult>.New(closure);
            }

        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Impl<TLambda> New<TLambda>(TLambda Lambda = default)
            where TLambda : struct, IFunc<T, U, TResult>
        {
            return new Impl<TLambda>(Lambda);
        }
    }


    public struct ValueFunc<T, U, V, TResult>
        where T : struct
        where U : struct
        where V : struct
        where TResult : struct
    {
        public readonly ref struct Impl<TLambda>
            where TLambda : struct, IFunc<T, U, V, TResult>
        {
            public readonly TLambda Lambda;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public TResult Invoke(T arg0, U arg1, V arg2)
            {
                return Lambda.Invoke(arg0, arg1, arg2);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal Impl(TLambda Lambda)
            {
                this.Lambda = Lambda;
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<U, V, TResult>.Impl<Closure<T>.AppliedToFunc<U, V, TResult, TLambda>> PartialInvoke(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToFunc<U, V, TResult, TLambda>(
                    arg0,
                    in this
                );
                return ValueFunc<U, V, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<V, TResult>.Impl<Closure<T, U>.AppliedToFunc<V, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1
                )
            {
                var closure = new Closure<T, U>.AppliedToFunc<V, TResult, TLambda>(
                    arg0,
                    arg1,
                    in this
                );
                return ValueFunc<V, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<TResult>.Impl<Closure<T, U, V>.AppliedToFunc<TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2
                )
            {
                var closure = new Closure<T, U, V>.AppliedToFunc<TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    in this
                );
                return ValueFunc<TResult>.New(closure);
            }

        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Impl<TLambda> New<TLambda>(TLambda Lambda = default)
            where TLambda : struct, IFunc<T, U, V, TResult>
        {
            return new Impl<TLambda>(Lambda);
        }
    }


    public struct ValueFunc<T, U, V, W, TResult>
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where TResult : struct
    {
        public readonly ref struct Impl<TLambda>
            where TLambda : struct, IFunc<T, U, V, W, TResult>
        {
            public readonly TLambda Lambda;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public TResult Invoke(T arg0, U arg1, V arg2, W arg3)
            {
                return Lambda.Invoke(arg0, arg1, arg2, arg3);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal Impl(TLambda Lambda)
            {
                this.Lambda = Lambda;
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<U, V, W, TResult>.Impl<Closure<T>.AppliedToFunc<U, V, W, TResult, TLambda>> PartialInvoke(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToFunc<U, V, W, TResult, TLambda>(
                    arg0,
                    in this
                );
                return ValueFunc<U, V, W, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<V, W, TResult>.Impl<Closure<T, U>.AppliedToFunc<V, W, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1
                )
            {
                var closure = new Closure<T, U>.AppliedToFunc<V, W, TResult, TLambda>(
                    arg0,
                    arg1,
                    in this
                );
                return ValueFunc<V, W, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<W, TResult>.Impl<Closure<T, U, V>.AppliedToFunc<W, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2
                )
            {
                var closure = new Closure<T, U, V>.AppliedToFunc<W, TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    in this
                );
                return ValueFunc<W, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<TResult>.Impl<Closure<T, U, V, W>.AppliedToFunc<TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2,
                W arg3
                )
            {
                var closure = new Closure<T, U, V, W>.AppliedToFunc<TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    in this
                );
                return ValueFunc<TResult>.New(closure);
            }

        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Impl<TLambda> New<TLambda>(TLambda Lambda = default)
            where TLambda : struct, IFunc<T, U, V, W, TResult>
        {
            return new Impl<TLambda>(Lambda);
        }
    }


    public struct ValueFunc<T, U, V, W, X, TResult>
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where X : struct
        where TResult : struct
    {
        public readonly ref struct Impl<TLambda>
            where TLambda : struct, IFunc<T, U, V, W, X, TResult>
        {
            public readonly TLambda Lambda;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public TResult Invoke(T arg0, U arg1, V arg2, W arg3, X arg4)
            {
                return Lambda.Invoke(arg0, arg1, arg2, arg3, arg4);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal Impl(TLambda Lambda)
            {
                this.Lambda = Lambda;
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<U, V, W, X, TResult>.Impl<Closure<T>.AppliedToFunc<U, V, W, X, TResult, TLambda>> PartialInvoke(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToFunc<U, V, W, X, TResult, TLambda>(
                    arg0,
                    in this
                );
                return ValueFunc<U, V, W, X, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<V, W, X, TResult>.Impl<Closure<T, U>.AppliedToFunc<V, W, X, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1
                )
            {
                var closure = new Closure<T, U>.AppliedToFunc<V, W, X, TResult, TLambda>(
                    arg0,
                    arg1,
                    in this
                );
                return ValueFunc<V, W, X, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<W, X, TResult>.Impl<Closure<T, U, V>.AppliedToFunc<W, X, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2
                )
            {
                var closure = new Closure<T, U, V>.AppliedToFunc<W, X, TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    in this
                );
                return ValueFunc<W, X, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<X, TResult>.Impl<Closure<T, U, V, W>.AppliedToFunc<X, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2,
                W arg3
                )
            {
                var closure = new Closure<T, U, V, W>.AppliedToFunc<X, TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    in this
                );
                return ValueFunc<X, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<TResult>.Impl<Closure<T, U, V, W, X>.AppliedToFunc<TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2,
                W arg3,
                X arg4
                )
            {
                var closure = new Closure<T, U, V, W, X>.AppliedToFunc<TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4,
                    in this
                );
                return ValueFunc<TResult>.New(closure);
            }

        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Impl<TLambda> New<TLambda>(TLambda Lambda = default)
            where TLambda : struct, IFunc<T, U, V, W, X, TResult>
        {
            return new Impl<TLambda>(Lambda);
        }
    }


    public struct ValueFunc<T, U, V, W, X, Y, TResult>
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where X : struct
        where Y : struct
        where TResult : struct
    {
        public readonly ref struct Impl<TLambda>
            where TLambda : struct, IFunc<T, U, V, W, X, Y, TResult>
        {
            public readonly TLambda Lambda;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public TResult Invoke(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5)
            {
                return Lambda.Invoke(arg0, arg1, arg2, arg3, arg4, arg5);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal Impl(TLambda Lambda)
            {
                this.Lambda = Lambda;
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<U, V, W, X, Y, TResult>.Impl<Closure<T>.AppliedToFunc<U, V, W, X, Y, TResult, TLambda>> PartialInvoke(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToFunc<U, V, W, X, Y, TResult, TLambda>(
                    arg0,
                    in this
                );
                return ValueFunc<U, V, W, X, Y, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<V, W, X, Y, TResult>.Impl<Closure<T, U>.AppliedToFunc<V, W, X, Y, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1
                )
            {
                var closure = new Closure<T, U>.AppliedToFunc<V, W, X, Y, TResult, TLambda>(
                    arg0,
                    arg1,
                    in this
                );
                return ValueFunc<V, W, X, Y, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<W, X, Y, TResult>.Impl<Closure<T, U, V>.AppliedToFunc<W, X, Y, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2
                )
            {
                var closure = new Closure<T, U, V>.AppliedToFunc<W, X, Y, TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    in this
                );
                return ValueFunc<W, X, Y, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<X, Y, TResult>.Impl<Closure<T, U, V, W>.AppliedToFunc<X, Y, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2,
                W arg3
                )
            {
                var closure = new Closure<T, U, V, W>.AppliedToFunc<X, Y, TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    in this
                );
                return ValueFunc<X, Y, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<Y, TResult>.Impl<Closure<T, U, V, W, X>.AppliedToFunc<Y, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2,
                W arg3,
                X arg4
                )
            {
                var closure = new Closure<T, U, V, W, X>.AppliedToFunc<Y, TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4,
                    in this
                );
                return ValueFunc<Y, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<TResult>.Impl<Closure<T, U, V, W, X, Y>.AppliedToFunc<TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2,
                W arg3,
                X arg4,
                Y arg5
                )
            {
                var closure = new Closure<T, U, V, W, X, Y>.AppliedToFunc<TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4,
                    arg5,
                    in this
                );
                return ValueFunc<TResult>.New(closure);
            }

        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Impl<TLambda> New<TLambda>(TLambda Lambda = default)
            where TLambda : struct, IFunc<T, U, V, W, X, Y, TResult>
        {
            return new Impl<TLambda>(Lambda);
        }
    }


    public struct ValueFunc<T, U, V, W, X, Y, Z, TResult>
        where T : struct
        where U : struct
        where V : struct
        where W : struct
        where X : struct
        where Y : struct
        where Z : struct
        where TResult : struct
    {
        public readonly ref struct Impl<TLambda>
            where TLambda : struct, IFunc<T, U, V, W, X, Y, Z, TResult>
        {
            public readonly TLambda Lambda;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public TResult Invoke(T arg0, U arg1, V arg2, W arg3, X arg4, Y arg5, Z arg6)
            {
                return Lambda.Invoke(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal Impl(TLambda Lambda)
            {
                this.Lambda = Lambda;
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<U, V, W, X, Y, Z, TResult>.Impl<Closure<T>.AppliedToFunc<U, V, W, X, Y, Z, TResult, TLambda>> PartialInvoke(
                T arg0
                )
            {
                var closure = new Closure<T>.AppliedToFunc<U, V, W, X, Y, Z, TResult, TLambda>(
                    arg0,
                    in this
                );
                return ValueFunc<U, V, W, X, Y, Z, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<V, W, X, Y, Z, TResult>.Impl<Closure<T, U>.AppliedToFunc<V, W, X, Y, Z, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1
                )
            {
                var closure = new Closure<T, U>.AppliedToFunc<V, W, X, Y, Z, TResult, TLambda>(
                    arg0,
                    arg1,
                    in this
                );
                return ValueFunc<V, W, X, Y, Z, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<W, X, Y, Z, TResult>.Impl<Closure<T, U, V>.AppliedToFunc<W, X, Y, Z, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2
                )
            {
                var closure = new Closure<T, U, V>.AppliedToFunc<W, X, Y, Z, TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    in this
                );
                return ValueFunc<W, X, Y, Z, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<X, Y, Z, TResult>.Impl<Closure<T, U, V, W>.AppliedToFunc<X, Y, Z, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2,
                W arg3
                )
            {
                var closure = new Closure<T, U, V, W>.AppliedToFunc<X, Y, Z, TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    in this
                );
                return ValueFunc<X, Y, Z, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<Y, Z, TResult>.Impl<Closure<T, U, V, W, X>.AppliedToFunc<Y, Z, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2,
                W arg3,
                X arg4
                )
            {
                var closure = new Closure<T, U, V, W, X>.AppliedToFunc<Y, Z, TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4,
                    in this
                );
                return ValueFunc<Y, Z, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<Z, TResult>.Impl<Closure<T, U, V, W, X, Y>.AppliedToFunc<Z, TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2,
                W arg3,
                X arg4,
                Y arg5
                )
            {
                var closure = new Closure<T, U, V, W, X, Y>.AppliedToFunc<Z, TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4,
                    arg5,
                    in this
                );
                return ValueFunc<Z, TResult>.New(closure);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public ValueFunc<TResult>.Impl<Closure<T, U, V, W, X, Y, Z>.AppliedToFunc<TResult, TLambda>> PartialInvoke(
                T arg0,
                U arg1,
                V arg2,
                W arg3,
                X arg4,
                Y arg5,
                Z arg6
                )
            {
                var closure = new Closure<T, U, V, W, X, Y, Z>.AppliedToFunc<TResult, TLambda>(
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4,
                    arg5,
                    arg6,
                    in this
                );
                return ValueFunc<TResult>.New(closure);
            }

        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Impl<TLambda> New<TLambda>(TLambda Lambda = default)
            where TLambda : struct, IFunc<T, U, V, W, X, Y, Z, TResult>
        {
            return new Impl<TLambda>(Lambda);
        }
    }


}
