name: Initialize Package

on: 
  workflow_dispatch:
    inputs:
      organizationPascal:
        description: 'The name of the organization in PascalCase.'
        required: true
      organizationKebab:
        description: 'The name of the organization in kebab-case.'
        required: true
      packagePascal:
        description: 'The name of the package in PascalCase.'
        required: true
      packageKebab:
        description: 'The name of the package in kebab-case'
        required: true

jobs:
  initialization:
    name: Initialize Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find and Replace Package Name
        env:
          ORGANIZATION_PASCAL: ${{ github.event.inputs.organizationPascal }}
          ORGANIZATION_KEBAB: ${{ github.event.inputs.organizationKebab }}
          PACKAGE_PASCAL: ${{ github.event.inputs.packagePascal }}
          PACKAGE_KEBAB: ${{ github.event.inputs.packageKebab }}
        run: |
          ./scripts/init
          rm ./scripts/init
          rm .github/workflows/init.yaml
      
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: Initialize Package [skip ci]'
