name: Unity Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2020_1 }}

jobs:
  testAllModes:
    name: Test on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2020.1.2f1

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
      - name: Cache Library
        uses: actions/cache@v2.1.1
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-
            Library-${{ matrix.projectPath }}-
            Library-
      - run: ./scripts/coverageAssemblyFilters
        id: assemblyFilters
      - uses: webbertakken/unity-test-runner@v1.6
        id: tests
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          artifactsPath: TestResults
          customParameters: -enableCodeCoverage -coverageOptions generateAdditionalMetrics;enableCyclomaticComplexity;assemblyFilters:${{ steps.assemblyFilters.outputs.result }}
      - name: Upload Test Results Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}
      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Code Coverage
          path: ./CodeCoverage
      - name: Upload PlayMode Test Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: ./CodeCoverage/workspace-opencov/PlayMode/TestCoverageResults_0000.xml
      - name: Upload EditMode Test Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: ./CodeCoverage/workspace-opencov/EditMode/TestCoverageResults_0000.xml
